### ISSUE TITLE
Android Webview issues?

### ISSUE THREAD

**Issue by tehmaestro** [CreateJS/SoundJS#164] opened 2015-05-05 06:57 UTC
Hi. I'm trying to use soundJS in an Android Webview. The problem is that when calling `play()`, the state goes to `playFailed` and the AJAX request is marked as `Cancelled`
  Is this  known issue?

**Comment by OJayRobinson** [comment] 2015-05-05 15:36
Assuming that with the Webview you have the files locally, the default WebAudioPlugin will have problems because it requires XHR to load which is not available locally.  If you are wrapping in something like PhoneGap, you can try the new CordovaAudioPlugin with SoundJS-Next.

Otherwise you can try forcing the plugin to HTMLAudioPlugin using [createjs.Sound.registerPlugins](http://www.createjs.com/Docs/SoundJS/classes/Sound.html#method_registerPlugins).

Hope that helps.

**Comment by tehmaestro** [comment] 2015-05-06 06:32
Hi. The files are not store locally, they are on a CDN. A XHR request is needed.
  I tried forcing to HTMLAudio, but still no sound.

**Comment by OJayRobinson** [comment] 2015-05-06 15:37
hmm, well that's not good.  For starters, please grab the latest SoundJS-Next and give it a try.

Next, does the code work when you locally host it rather than having it in a webview?  If not, then the issue is code or audio encoding related and not webview related.

Next, does the [Sound Grid Demo](http://www.createjs.com/Demos/SoundJS/SoundGrid) work on your device?  If not, it's a device issue.

Finally, the [Mobile Safe Tutorial](http://www.createjs.com/tutorials/Mobile%20Safe%20Approach/) has solutions to some common mobile issues, for example sounds needing to be played in a user event.  So that may be of use.

Hopefully one of these solutions will work for you.  If not, we'll dig deeper.

**Comment by tehmaestro** [comment] 2015-05-07 09:22
I just tried your demo, and it's the same, the XHR requests to the OGG files are getting cancelled.
This is what I'm seeing in the chrome console for the request:
```
   Request URL:http://www.createjs.com/demos/_assets/audio/Thunder1.ogg
   Request Headers CAUTION: Provisional headers are shown.
   Cache-Control:no-cache
   Pragma:no-cache
   Referer:http://www.createjs.com/demos/soundjs/TestSuite.html
   User-Agent:Mozilla/5.0 (Linux; Android 4.4.4; D2303 Build/18.3.1.C.0.21) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36
```

**Comment by OJayRobinson** [comment] 2015-05-07 16:20
From the repo, can you grab /examples/06_MobileSafe.html and it's related assets, change the audio src to load something that is not local, and try it in a webview and let me know what happens.

**Comment by tehmaestro** [comment] 2015-05-07 17:06
Thank you so much for the help.
  I did try your demo, both with the original src, and with my CDN located filed, still, same result. I created a screenshot, seems like there are 2 requests launching ...
http://postimg.org/image/6nhz2825n/

**Comment by OJayRobinson** [comment] 2015-05-08 15:39
That's somewhat baffling, there is nothing in the SoundJS code that would cancel a load.  The MobileSafe example has been successfully tested in older versions of Android stock browser which is the base for older webviews, but never tested inside a webview.  It seems like something else is causing this behavior, but I can't image what could be doing that.  I just want to confirm, do the examples work when you just run them in a browser (outside of a webview)?

Can you try loading a single file with PreloadJS and listening for all the loading events (error, etc).

I'll try to make some time to test this out locally, but am overly busy at the moment so it might be awhile.

**Comment by tehmaestro** [comment] 2015-05-08 15:45
Yes, the examples work in the browser. My app also works in the browser, but not inside a webview.
 I'll try to include PreloadJS.

**Comment by OJayRobinson** [comment] 2015-05-08 15:48
A colleague suggested to me that perhaps the webview doesn't properly support ogg files, so maybe try switching filetype to mp3 as a quick sanity test.

**Comment by tehmaestro** [comment] 2015-05-08 15:49
I'm actually using mp3's. And your examples have ogg.

**Comment by OJayRobinson** [comment] 2015-05-12 15:52
cool, glad you found a solution you like.  I agree that it is a device / webview problem, so I'll close this issue as I don't think SoundJS can overcome it.

**Closed by OJayRobinson** 2015-05-12 15:52 UTC
