### ISSUE TITLE
Sound skips in Firefox, jerks in Chrome

### ISSUE THREAD

**Issue by metalim** [CreateJS/SoundJS#189] opened 2015-08-06 08:21 UTC
Listening to http://createjs.com/demos/soundjs/mediaplayer

In Firefox 39.0 music skips every few seconds.

In Chrome 44.0.2403.130 music "jerks" (like scratching a vinyl) every few seconds, where it was skipping in Firefox. Also audio plays in right channel only (in Firefox it was stereo)

**Comment by probil** [comment] 2015-08-21 08:29
The same issue. 

Chrome 44.0.2403.157 (64-bit), Linux

**Comment by probil** [comment] 2015-08-21 09:04
Sound "jerks" is a sound specific issue. I downloaded it and play view standalone player and it also glitches. So the issue is one channel audio playing on chrome.

If you set HTMLAudio as a default audio plugin it plays in two channel
```
createjs.Sound.registerPlugins([createjs.HTMLAudioPlugin,createjs.WebAudioPlugin]);
```

**Comment by probil** [comment] 2015-08-21 09:06
I have found this sound without "jerks"
```
http://www.pirateslovedaisies.com/audio/music/M-GameBackground.mp3
```

**Comment by JamesMilnerUK** [comment] 2015-10-15 10:04
@probil your solution of changing the default audio plugin works more generally for the issue in Chrome of mono sound playing for MP3s (doesn't seem to be an issue on Firefox). Do you know why the default plugin (whichever that is) plays mono on Chrome?

**Comment by probil** [comment] 2015-10-15 14:09
@JamesMilnerUK Don't really know. On my project I have replaced SoundJS stable (0.6.1) with SoundJS NEXT. And now, it works well, even with default plugin.

You could get NEXT version here
https://github.com/CreateJS/SoundJS/tree/master/lib

**Comment by lannymcnie** [comment] 2015-10-15 15:09
Yes, this has been fixed in NEXT, and we are hoping to get a hotfix for 0.6.1 on the CDN shortly. Cheers.

**Comment by lannymcnie** [comment] 2015-11-09 18:10
Closing this issue. The sound channel issue in 0.6.1 has been hot-fixed on the CDN. There is also a HOTFIX branch in the SoundJS repository, which just has the single fix. 

Thanks for pointing out the issue with the sample sound file -- not sure when it got corrupted!

**Closed by lannymcnie** 2015-11-09 18:10 UTC
