### ISSUE TITLE
Chrome audio only working in one channel

### ISSUE THREAD

**Issue by bit-coursera** [CreateJS/SoundJS#192] opened 2015-08-17 18:51 UTC
On Chrome 44 with headset method createjs.Sound.play uses only right channel, on Firefox 40 both channels are used even on  [demo] ( http://www.createjs.com/getting-started/soundjs)

**Comment by gskinner** [comment] 2015-08-17 18:53
Duplicate of https://github.com/CreateJS/SoundJS/issues/182

**Closed by gskinner** 2015-08-17 18:53 UTC
Labels: duplicate
