### ISSUE TITLE
The demos on the webpage do not play on my left speaker

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [CreateJS/SoundJS#213] opened 2015-10-28 10:29 UTC
My friend confirmed. Not sure if the problem is with the files used or the whole library.

On both windows 8.1 and windows 10 with newest chrome

**Comment by lannymcnie** [comment] 2015-10-28 15:09
This is a duplicate of https://github.com/CreateJS/SoundJS/issues/182

This has been resolved in the latest NEXT version in GitHub, and patched on the CDN. If you need a version of 0.6.1, there is a branch for it in GitHub as well (https://github.com/CreateJS/SoundJS/tree/0.6.1-HOTFIX). The website might not have the latest version in the demos, so I will update it ASAP.

**Closed by lannymcnie** 2015-10-28 15:09 UTC
Labels: duplicate

**Comment by lannymcnie** [comment] 2015-10-28 16:28
This has been fixed on http://createjs.com. Thanks for the heads up.
